config/routes.rb
Rails.application.routes.draw do
  get 'new_pages/page1'

  get 'new_pages/page2'

  get 'new_pages/page3'

  root 'pages#home'
  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  end

  def about
  end

end

app/controllers/new_pages_controller.rb
class NewPagesController < ApplicationController
  def page1
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_pages_helper.rb
module NewPagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<% render 'partials/nav'%>

    <p>Everything on this page is factual</p>
<div class="container-fluid">

    <%= yield %>

</div>
  </body>
</html>

app/views/new_pages/page1.html.erb
<h1>NewPages#page1</h1>
<p>Find me in app/views/new_pages/page1.html.erb</p>

<%= link_to "Page1", new_pages_page1_path%>
<%= link_to "page2", new_pages_page2_path%>
<%= link_to "page3", new_pages_page3_path%>
<%= link_to "about", pages_about_path%>
<br>
<%= link_to "home", root_path%>

app/views/new_pages/page2.html.erb
<h1>NewPages#page2</h1>
<p>Find me in app/views/new_pages/page2.html.erb</p>

<%= link_to "Page1", new_pages_page1_path%>
<%= link_to "page2", new_pages_page2_path%>
<%= link_to "page3", new_pages_page3_path%>
<%= link_to "about", pages_about_path%>
<br>
<%= link_to "home", root_path%>

app/views/new_pages/page3.html.erb
<h1>NewPages#page3</h1>
<p>Find me in app/views/new_pages/page3.html.erb</p>

<%= link_to "Page1", new_pages_page1_path%>
<%= link_to "page2", new_pages_page2_path%>
<%= link_to "page3", new_pages_page3_path%>
<%= link_to "about", pages_about_path%>
<br>
<%= link_to "home", root_path%>

app/views/pages/about.html.erb
<h1>Trent is the best</h1>

<!-- <%= link_to "my first link", root_path%> -->

<%= link_to "Page1", new_pages_page1_path%>
<%= link_to "page2", new_pages_page2_path%>
<%= link_to "page3", new_pages_page3_path%>
<%= link_to "about", pages_about_path%>
<br>
<%= link_to "home", root_path%>

app/views/pages/home.html.erb
<%= 5.times do %>

<h1>Sup</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<!-- <% 5*5 %> -->
<% end %>

<%= link_to "Page1", new_pages_page1_path%>
<%= link_to "page2", new_pages_page2_path%>
<%= link_to "page3", new_pages_page3_path%>
<%= link_to "about", pages_about_path%>
<br>
<%= link_to "home", root_path%>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>